CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          username VARCHAR(255),
                          email VARCHAR(255),
                          password VARCHAR(255),
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          PRIMARY KEY (id)
);
